# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

        bind:
            Symfony\Component\Messenger\MessageBusInterface $commandBus: "@command.bus"
            Symfony\Component\Messenger\MessageBusInterface $queryBus: "@query.bus"
            Symfony\Component\Messenger\MessageBusInterface $eventBus: "@event.bus"
            Symfony\Component\Messenger\MessageBusInterface $projectionBus: "@projection.bus"

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    #App\:
    #    resource: '../src/'
    #    exclude:
    #        - '../src/DependencyInjection/'
    #        - '../src/Entity/'
    #        - '../src/Kernel.php'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    
    api_exception_subscriber:
        class: App\Shared\Infrastructure\Symfony\ExceptionEventListener
        arguments: [ ]
        tags:
            - { name: kernel.event_subscriber }
    
    App\:
        resource: '../src/'

    App\Shared\Application\Command\CommandBus:
        class: App\Shared\Infrastructure\Bus\SymfonyCommandBus
        
    App\Shared\Application\Query\QueryBus:
        class: App\Shared\Infrastructure\Bus\SymfonyQueryBus
        
    App\Shared\Application\Event\EventBus:
        class: App\Shared\Infrastructure\Bus\SymfonyEventBus
        
    App\Shared\Application\Projection\ProjectionBus:
        class: App\Shared\Infrastructure\Bus\SymfonyProjectionBus

    command_handlers:
        namespace: 'App\'
        resource: '../src/**/Application/**/*CommandHandler.php'
        tags:
            - { name: messenger.message_handler, bus: command.bus }

    query_handlers:
        namespace: 'App\'
        resource: '../src/**/Application/**/*QueryHandler.php'
        tags:
            - { name: messenger.message_handler, bus: query.bus }

    event_handlers:
        namespace: 'App\'
        resource: '../src/**/Application/**/Listeners/*.php'
        tags:
            - { name: messenger.message_handler, bus: event.bus }

    projection_handlers:
        namespace: 'App\'
        resource: '../src/**/Application/**/Projections/*.php'
        tags:
            - { name: messenger.message_handler, bus: projection.bus }

    modules:
        namespace: 'App\'
        resource: '../src/**/**/*Module.php'
    
    repositories:
        namespace: 'App\'
        resource: '../src/**/Domain/**/*Repository.php'
        
    routing:
        namespace: 'App\'
        resource: '../src/**/Interface/Api'
        tags: ['controller.service_arguments']

    App\Post\Infrastructure\Persistence\PostGatewayInterface:
        class: App\Post\Infrastructure\Persistence\Doctrine\DoctrinePostGateway
